import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Service | Forecoding",
  description: "Forecoding Terms of Service"
};

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-gray-50 dark:bg-gray-950 text-gray-900 dark:text-gray-100">
      <div className="mx-auto max-w-4xl px-6 py-12 space-y-8">
        <header className="space-y-3">
          <h1 className="text-3xl font-bold">Terms of Service</h1>
          <p className="text-sm text-gray-600 dark:text-gray-400">Effective Date: February 26, 2026</p>
          <p className="text-sm text-gray-600 dark:text-gray-400">
            These Terms of Service ("Terms") govern access to and use of Forecoding, operated by CIVRA LTD,
            71-75 Shelton Street, Covent Garden, London, England, WC2H 9JQ, United Kingdom.
          </p>
        </header>

        <article className="space-y-6 text-sm leading-7 text-gray-700 dark:text-gray-300">
          <section className="space-y-2">
            <h2 className="text-lg font-semibold text-gray-900 dark:text-gray-100">1. Acceptance</h2>
            <p>By accessing or using the Service, you agree to be bound by these Terms.</p>
          </section>

          <section className="space-y-2">
            <h2 className="text-lg font-semibold text-gray-900 dark:text-gray-100">2. Description of Service</h2>
            <p>Forecoding provides AI tools that generate:</p>
            <ul className="list-disc pl-6 space-y-1">
              <li>Product Requirement Documents (PRDs)</li>
              <li>Architecture diagrams</li>
              <li>Development task lists</li>
              <li>Code modification suggestions</li>
            </ul>
            <p>Outputs are generated by AI systems and may contain errors or inaccuracies.</p>
          </section>

          <section className="space-y-2">
            <h2 className="text-lg font-semibold text-gray-900 dark:text-gray-100">3. Accounts</h2>
            <p>Users must:</p>
            <ul className="list-disc pl-6 space-y-1">
              <li>Provide accurate email information</li>
              <li>Maintain credential confidentiality</li>
              <li>Accept responsibility for all account activity</li>
            </ul>
            <p>We reserve the right to suspend or terminate accounts for violations.</p>
          </section>

          <section className="space-y-2">
            <h2 className="text-lg font-semibold text-gray-900 dark:text-gray-100">4. Acceptable Use</h2>
            <p>You may not:</p>
            <ul className="list-disc pl-6 space-y-1">
              <li>Use the Service for unlawful purposes</li>
              <li>Infringe intellectual property rights</li>
              <li>Generate malicious code</li>
              <li>Circumvent usage limitations</li>
            </ul>
          </section>

          <section className="space-y-2">
            <h2 className="text-lg font-semibold text-gray-900 dark:text-gray-100">5. Intellectual Property</h2>
            <p>All platform software, systems, and infrastructure are owned by CIVRA LTD.</p>
            <p>Users retain ownership of their submitted input content.</p>
            <p>AI-generated outputs are provided without warranty of originality, accuracy, or non-infringement.</p>
          </section>

          <section className="space-y-2">
            <h2 className="text-lg font-semibold text-gray-900 dark:text-gray-100">6. AI Disclaimer</h2>
            <p>AI outputs are provided for informational purposes only.</p>
            <p>They do not constitute legal, technical, or professional advice.</p>
            <p>Users assume full responsibility for reliance on generated content.</p>
          </section>

          <section className="space-y-2">
            <h2 className="text-lg font-semibold text-gray-900 dark:text-gray-100">7. Payment Terms</h2>
            <ul className="list-disc pl-6 space-y-1">
              <li>Payments are processed via Stripe</li>
              <li>Purchases are one-time project credits</li>
              <li>No subscription is created</li>
              <li>Refunds are governed by the Refund Policy at /refund</li>
            </ul>
          </section>

          <section className="space-y-2">
            <h2 className="text-lg font-semibold text-gray-900 dark:text-gray-100">8. Arbitration (United States Users Only)</h2>
            <p>For U.S. residents:</p>
            <ul className="list-disc pl-6 space-y-1">
              <li>Disputes shall be resolved through binding arbitration under AAA Rules</li>
              <li>Class action participation is waived</li>
              <li>Users may opt out within 30 days of acceptance</li>
            </ul>
            <p>This clause does not apply where prohibited by local law.</p>
          </section>

          <section className="space-y-2">
            <h2 className="text-lg font-semibold text-gray-900 dark:text-gray-100">9. EU/UK Consumer Protection</h2>
            <p>Nothing in these Terms limits mandatory consumer protection rights under applicable EU or UK law.</p>
          </section>

          <section className="space-y-2">
            <h2 className="text-lg font-semibold text-gray-900 dark:text-gray-100">10. Limitation of Liability</h2>
            <p>To the maximum extent permitted by law:</p>
            <ul className="list-disc pl-6 space-y-1">
              <li>CIVRA LTD shall not be liable for indirect, incidental, or consequential damages</li>
              <li>Total liability shall not exceed the amount paid for the specific project credit</li>
            </ul>
          </section>

          <section className="space-y-2">
            <h2 className="text-lg font-semibold text-gray-900 dark:text-gray-100">11. DMCA Notice</h2>
            <p>To submit a copyright infringement notice, email: support@forecoding.com</p>
            <p>Include:</p>
            <ul className="list-disc pl-6 space-y-1">
              <li>Identification of copyrighted work</li>
              <li>URL of alleged infringement</li>
              <li>Contact information</li>
              <li>Good faith statement</li>
            </ul>
            <p>Counter-notice procedures are available upon request.</p>
          </section>

          <section className="space-y-2">
            <h2 className="text-lg font-semibold text-gray-900 dark:text-gray-100">12. Governing Law</h2>
            <p>For U.S. users: California law applies.</p>
            <p>For UK users: English law applies.</p>
            <p>For EU users: mandatory local consumer protections remain unaffected.</p>
          </section>

          <section className="space-y-2">
            <h2 className="text-lg font-semibold text-gray-900 dark:text-gray-100">13. Modifications</h2>
            <p>We may update these Terms at any time. Continued use constitutes acceptance.</p>
          </section>
        </article>

        <div className="pt-4 border-t border-gray-200 dark:border-gray-800">
          <Link href="/" className="text-sm text-blue-600 dark:text-blue-400 hover:underline">
            Back to Home
          </Link>
        </div>
      </div>
    </main>
  );
}
