import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Service | Forecoding",
  description: "Forecoding Terms of Service"
};

export default function TermsPage() {
  return (
    <main className="relative min-h-screen overflow-hidden text-slate-900 dark:text-slate-100">
      <div className="pointer-events-none absolute inset-0">
        <div className="fc-float absolute -top-20 -left-20 h-72 w-72 rounded-full bg-blue-500/20 blur-3xl" />
        <div className="fc-float absolute right-0 top-1/3 h-72 w-72 rounded-full bg-cyan-500/20 blur-3xl" style={{ animationDelay: "1.1s" }} />
      </div>
      <div className="relative mx-auto max-w-4xl px-4 py-8 sm:px-6">
        <div className="fc-surface-strong space-y-8 rounded-[var(--radius-2xl)] p-6 sm:p-8">
        <header className="space-y-3 border-b border-[color:var(--border)] pb-6">
          <h1 className="text-3xl font-semibold text-slate-900 dark:text-slate-100">Terms of Service</h1>
          <p className="text-sm text-slate-500 dark:text-slate-300">Effective Date: February 26, 2026</p>
          <p className="text-sm text-slate-500 dark:text-slate-300">
            These Terms of Service (&quot;Terms&quot;) govern access to and use of Forecoding, operated by Forecoding.
          </p>
        </header>

        <article className="space-y-6 text-sm leading-7 text-slate-700 dark:text-slate-300">
          <section className="space-y-2">
            <h2 className="text-lg font-semibold text-gray-900 dark:text-gray-100">1. Acceptance</h2>
            <p>By accessing or using the Service, you agree to be bound by these Terms.</p>
          </section>

          <section className="space-y-2">
            <h2 className="text-lg font-semibold text-gray-900 dark:text-gray-100">2. Description of Service</h2>
            <p>Forecoding provides AI tools that generate:</p>
            <ul className="list-disc pl-6 space-y-1">
              <li>Product Requirement Documents (PRDs)</li>
              <li>Architecture diagrams</li>
              <li>Development task lists</li>
              <li>Code modification suggestions</li>
            </ul>
            <p>Outputs are generated by AI systems and may contain errors or inaccuracies.</p>
          </section>

          <section className="space-y-2">
            <h2 className="text-lg font-semibold text-gray-900 dark:text-gray-100">3. Accounts</h2>
            <p>Users must:</p>
            <ul className="list-disc pl-6 space-y-1">
              <li>Provide accurate email information</li>
              <li>Maintain credential confidentiality</li>
              <li>Accept responsibility for all account activity</li>
            </ul>
            <p>We reserve the right to suspend or terminate accounts for violations.</p>
          </section>

          <section className="space-y-2">
            <h2 className="text-lg font-semibold text-gray-900 dark:text-gray-100">4. Acceptable Use</h2>
            <p>You may not:</p>
            <ul className="list-disc pl-6 space-y-1">
              <li>Use the Service for unlawful purposes</li>
              <li>Infringe intellectual property rights</li>
              <li>Generate malicious code</li>
              <li>Circumvent usage limitations</li>
            </ul>
          </section>

          <section className="space-y-2">
            <h2 className="text-lg font-semibold text-gray-900 dark:text-gray-100">5. Intellectual Property</h2>
            <p>All platform software, systems, and infrastructure are owned by Forecoding.</p>
            <p>Users retain ownership of their submitted input content.</p>
            <p>AI-generated outputs are provided without warranty of originality, accuracy, or non-infringement.</p>
          </section>

          <section className="space-y-2">
            <h2 className="text-lg font-semibold text-gray-900 dark:text-gray-100">6. AI Disclaimer</h2>
            <p>AI outputs are provided for informational purposes only.</p>
            <p>They do not constitute legal, technical, or professional advice.</p>
            <p>Users assume full responsibility for reliance on generated content.</p>
          </section>

          <section className="space-y-2">
            <h2 className="text-lg font-semibold text-gray-900 dark:text-gray-100">7. Payment Terms</h2>
            <ul className="list-disc pl-6 space-y-1">
              <li>Payments are processed via Stripe</li>
              <li>Purchases are one-time project credits</li>
              <li>No subscription is created</li>
              <li>Refunds are governed by the Refund Policy at /refund</li>
            </ul>
          </section>

          <section className="space-y-2">
            <h2 className="text-lg font-semibold text-gray-900 dark:text-gray-100">8. Arbitration (United States Users Only)</h2>
            <p>For U.S. residents:</p>
            <ul className="list-disc pl-6 space-y-1">
              <li>Disputes shall be resolved through binding arbitration under AAA Rules</li>
              <li>Class action participation is waived</li>
              <li>Users may opt out within 30 days of acceptance</li>
            </ul>
            <p>This clause does not apply where prohibited by local law.</p>
          </section>

          <section className="space-y-2">
            <h2 className="text-lg font-semibold text-gray-900 dark:text-gray-100">9. EU/UK Consumer Protection</h2>
            <p>Nothing in these Terms limits mandatory consumer protection rights under applicable EU or UK law.</p>
          </section>

          <section className="space-y-2">
            <h2 className="text-lg font-semibold text-gray-900 dark:text-gray-100">10. Limitation of Liability</h2>
            <p>To the maximum extent permitted by law:</p>
            <ul className="list-disc pl-6 space-y-1">
              <li>Forecoding shall not be liable for indirect, incidental, or consequential damages</li>
              <li>Total liability shall not exceed the amount paid for the specific project credit</li>
            </ul>
          </section>

          <section className="space-y-2">
            <h2 className="text-lg font-semibold text-gray-900 dark:text-gray-100">11. DMCA Notice</h2>
            <p>To submit a copyright infringement notice, email: support@forecoding.com</p>
            <p>Include:</p>
            <ul className="list-disc pl-6 space-y-1">
              <li>Identification of copyrighted work</li>
              <li>URL of alleged infringement</li>
              <li>Contact information</li>
              <li>Good faith statement</li>
            </ul>
            <p>Counter-notice procedures are available upon request.</p>
          </section>

          <section className="space-y-2">
            <h2 className="text-lg font-semibold text-gray-900 dark:text-gray-100">12. Governing Law</h2>
            <p>For U.S. users: California law applies.</p>
            <p>For UK users: English law applies.</p>
            <p>For EU users: mandatory local consumer protections remain unaffected.</p>
          </section>

          <section className="space-y-2">
            <h2 className="text-lg font-semibold text-gray-900 dark:text-gray-100">13. Modifications</h2>
            <p>We may update these Terms at any time. Continued use constitutes acceptance.</p>
          </section>
        </article>

        <div className="pt-4 border-t border-[color:var(--border)]">
          <Link href="/" className="fc-button-secondary inline-flex items-center px-4 py-2 text-sm font-semibold">
            Back to Home
          </Link>
        </div>
        </div>
      </div>
    </main>
  );
}
